name: Install and Build Backend

on:
  push:
    branches:
      - main  # Cambia con il nome del branch se necessario
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Sostituisci con la versione di Node.js che ti serve

    - name: Install dependencies in backend
      working-directory: ./backend  # Indica la cartella backend
      run: npm install

    - name: Run the application
      working-directory: ./backend  # Indica la cartella backend
      run: npm start  # Cambia con il comando per avviare il server se diverso
